name: Build

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.22.0'
      - run: go version

      - name: Test
        run: |
          go test -v ./cmd ./internal

      - name: Build
        run: |
          go build -o ieftool
